### ISSUE TITLE
need clarity on what this mode actually does

### ISSUE THREAD

**Issue by aspiers** [aspiers/smooth-scrolling#15]
I'm no longer clear (or I forgot) what advantages this package brings over tweaking a few built-in variables, e.g. my custom file has:

```
 '(scroll-conservatively 2)
 '(scroll-margin 20)
 '(scroll-preserve-screen-position t)
```

and that seems to give me behaviour devoid of anything annoying, unlike the situation which originally prompted me to write this package.

Plus it's likely that emacs' built-in behaviour has changed for the better during the several major releases since I originally wrote this.  Worse still, https://www.emacswiki.org/emacs/SmoothScrolling is an utterly and hopelessly confusing mess.

The package has:

```
;;; Commentary:

;; Make emacs scroll smoothly, keeping the point away from the top and
;; bottom of the current buffer's window in order to keep lines of
;; context around the point visible as much as possible, whilst
;; avoiding sudden scroll jumps which are visually confusing.
;;
;; This is a nice alternative to all the native scroll-* custom
;; variables, which unfortunately cannot provide this functionality
;; perfectly.  `scroll-margin' comes closest, but has some bugs
;; (e.g. with handling of mouse clicks).  See
;;
;;   http://www.emacswiki.org/cgi-bin/wiki/SmoothScrolling
;;
;; for the gory details.
```

but this no longer matches my experience.  @DarwinAwardWinner, please can you help clarify this?

**Comment by DarwinAwardWinner** [comment]
I recall two main advantages. First, with the built-in emacs "smooth scrolling", clicking with the mouse in the margin will immediately scroll the window to maintain the margin, so the text that you clicked on will no longer be under the mouse, which can be disorienting, whereas this mode will not do any scrolling until you actually move up or down a line. See (https://github.com/aspiers/smooth-scrolling/blob/master/smooth-scrolling.el#L138-L143). Second, the built-in margin code does not interact well with small windows. If the margin is more than half the window height, you get some weird behavior, because the point is always hitting both the top and bottom margins. This package auto-adjusts the margin in each buffer to never exceed half the window height, so the top and bottom margins never overlap. (See https://github.com/aspiers/smooth-scrolling/blob/master/smooth-scrolling.el#L145-L149).

**Comment by aspiers** [comment]
Thank you, that is extremely helpful!  My memory of this was all incredibly hazy.  I'll update the README accordingly.

**Comment by DarwinAwardWinner** [comment]
Yeah, it was hazy for me too. It's a good thing I wrote that commentary.
